name: G-Zone Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Run npm ci
        run: npm ci
      - name: install dotenv
        run: npm install dotenv
      - name: Run npm run build
        run: npm run build
        env:
          NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
          NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          NEXT_PUBLIC_SANITY_TITLE: ${{ secrets.NEXT_PUBLIC_SANITY_TITLE }}
          NEXT_PUBLIC_SANITY_DESCRIPTION: ${{ secrets.NEXT_PUBLIC_SANITY_DESCRIPTION }}
          NEXT_PUBLIC_SITE_MODE: ${{ secrets.NEXT_PUBLIC_SITE_MODE }}
