name: G-Zone Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Run npm ci
        run: npm ci
      - name: Run npm run build
        run: npm run build
